force-app/main/default/objects/Case/fields/CategoryLevel1__c.field-meta.xml
<CustomField>
    <fullName>CategoryLevel1__c</fullName>
    <label>Category Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatingCompany__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CategoryLevel1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CategoryLevel2__c.field-meta.xml
<CustomField>
    <fullName>CategoryLevel2__c</fullName>
    <label>Category Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CategoryLevel1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CategoryLevel2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.OperatingCompany__c, &quot;Plantyn&quot;), &quot;Plantyn&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Liber&quot;), &quot;Liber&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff&quot;), &quot;Noordhoff&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff Professional&quot;), &quot;Noordhoff&quot;,
&quot;&quot;))))</defaultValue>
    <label>Operating Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OperatingCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Noordhoff.recordType-meta.xml
<RecordType>
    <fullName>Noordhoff</fullName>
    <active>true</active>
    <businessProcess>Support Process</businessProcess>
    <label>Noordhoff</label>
</RecordType>

force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/CategoryLevel2__c.field-meta.xml
<CustomField>
    <fullName>CategoryLevel2__c</fullName>
    <description>CategoryLevel2</description>
    <label>Category Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatingCompany__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CategoryLevel2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.OperatingCompany__c, &quot;Plantyn&quot;), &quot;Plantyn&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Liber&quot;), &quot;Liber&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff&quot;), &quot;Noordhoff&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff Zorg&quot;), &quot;Noordhoff&quot;,
&quot;&quot;))))</defaultValue>
    <label>Operating Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OperatingCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/PrimaryEducation__c.field-meta.xml
<CustomField>
    <fullName>PrimaryEducation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Education</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>How to</fullName>
            </value>
            <value>
                <fullName>FAQ</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>News &amp; Updates</fullName>
                <isActive>false</isActive>
                <label>News &amp; Updates</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CategoryLevel1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Primary Education</fullName>
    </customValue>
    <customValue>
        <fullName>Secondary Education</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational Education</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>Hoger onderwijs</fullName>
        <isActive>false</isActive>
        <label>Hoger onderwijs</label>
    </customValue>
    <customValue>
        <fullName>Middelbaar beroepsonderwijs</fullName>
        <isActive>false</isActive>
        <label>Middelbaar beroepsonderwijs</label>
    </customValue>
    <customValue>
        <fullName>Voortgezet onderwijs</fullName>
        <isActive>false</isActive>
        <label>Voortgezet onderwijs</label>
    </customValue>
    <customValue>
        <fullName>Basisonderwijs</fullName>
        <isActive>false</isActive>
        <label>Basisonderwijs</label>
    </customValue>
    <customValue>
        <fullName>Algemeen</fullName>
        <isActive>false</isActive>
        <label>Algemeen</label>
    </customValue>
    <masterLabel>Category Level 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CategoryLevel2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assortiment</fullName>
    </customValue>
    <customValue>
        <fullName>Bestelling &amp; Levering</fullName>
    </customValue>
    <customValue>
        <fullName>Klantgegevens &amp; Account</fullName>
    </customValue>
    <customValue>
        <fullName>Factuur &amp; Betaling</fullName>
    </customValue>
    <customValue>
        <fullName>Werken met het digitaal lesmateriaal</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Werken met het digitaal materiaal</fullName>
        <isActive>false</isActive>
        <label>Werken met het digitaal materiaal</label>
    </customValue>
    <masterLabel>Category Level 2</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OperatingCompany.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Liber</fullName>
    </customValue>
    <customValue>
        <fullName>Noordhoff</fullName>
    </customValue>
    <customValue>
        <fullName>Plantyn</fullName>
    </customValue>
    <customValue>
        <fullName>Infinitas Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Noordhoff Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Professional</fullName>
        <isActive>false</isActive>
        <label>Professional</label>
    </customValue>
    <masterLabel>Operating Company</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CASE_CaseHelper_TEST.cls
@IsTest
public class CASE_CaseHelper_TEST {
    
    @TestSetup
    static void makeData(){

        // Get Noordhoff Case recordtypeId
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Noordhoff').getRecordTypeId();

        // Get Noordhoff BusinessHoursId
        Id businessHoursId = [SELECT Id FROM BusinessHours WHERE Name = 'Noordhoff' LIMIT 1].Id;

        // Create Case
        Case c = new Case();
        c.recordTypeId = recordTypeId;
        c.Status = 'New';
        c.Origin = 'Phone';
        c.CategoryLevel1__c = 'General';
        c.CategoryLevel2__c = 'Assortiment';
        c.BusinessHoursId = businessHoursId;

        insert c;

        // Create 3 Knowledge Articles
        List<knowledge__kav> newArticleList = new List<knowledge__kav>();
        for (Integer i = 0; i < 3; i++) {
            knowledge__kav newArticle = new knowledge__kav();
            newArticle.Title = 'Test Article ' + (i+1);
            newArticle.Content__c = 'Test Content for Article ' + (i+1);
            newArticle.Type__c = 'FAQ';
            newArticle.UrlName = 'testUrl'+(i+1);
            newArticle.OperatingCompany__c = 'Noordhoff';
            newArticle.PrimaryEducation__c = true;
            newArticleList.add(newArticle);
        }
        insert newArticleList;

        // Get knowledgaArticle Ids
        List<Knowledge__Kav> kavList = [SELECT Id, KnowledgeArticleId FROM Knowledge__kav];
        List<CaseArticle> caList = new List<CaseArticle>();
        for (Knowledge__kav k : kavList) {
            
            // publish article
            KbManagement.PublishingService.publishArticle(k.KnowledgeArticleId, true);
            
            // Attach Articles to Case
            CaseArticle ca = new CaseArticle();
            ca.caseId = c.Id;
            ca.KnowledgeArticleId = k.KnowledgeArticleId;
            caList.add(ca);
        }
        insert caList;
    }

    @IsTest
    static void Test01(){
        
        List<Case> c = [SELECT Id FROM Case];

        CASE_CaseHelper.parameters param = new CASE_CaseHelper.parameters();
        param.inputCase = c[0];

        List<CASE_CaseHelper.parameters> paramList = new List<CASE_CaseHelper.parameters>();
        paramList.add(param);

        Test.startTest();
            List<Integer> numberOfArticles = CASE_CaseHelper.getNumberOfArticlesFromCase(paramList);
        Test.stopTest();
        
        System.assertEquals(3, numberOfArticles[0], 'We received an incorrect amount of articles, expected: 3, we got: ' + numberOfArticles[0]);
    }

}