force-app/main/default/objects/Account/fields/AgodiUpdateInProgress__c.field-meta.xml
<CustomField>
    <fullName>AgodiUpdateInProgress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agodi update in progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingReminderEmail__c.field-meta.xml
<CustomField>
    <fullName>BillingReminderEmail__c</fullName>
    <label>Billing Reminder Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AccountClassifications</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CommunicationLanguage__c.field-meta.xml
<CustomField>
    <fullName>CommunicationLanguage__c</fullName>
    <defaultValue>IF(OR(ISPICKVAL($User.OperatingCompany__c , &apos;Noordhoff&apos;),ISPICKVAL($User.OperatingCompany__c , &apos;Noordhoff Professional&apos;)), &apos;nl_NL&apos;,
IF(ISPICKVAL($User.OperatingCompany__c , &apos;Liber&apos;), &apos;sv_SE&apos;, &apos;&apos;))</defaultValue>
    <inlineHelpText>All order confirmations, quotes and invoices will be sent based on this language.</inlineHelpText>
    <label>Communication Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Communication_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Courier__c.field-meta.xml
<CustomField>
    <fullName>Courier__c</fullName>
    <description>This information is mandatory for Förlagssystem in the shipping messages sent from integrations.</description>
    <label>Courier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Courier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerCategory__c.field-meta.xml
<CustomField>
    <fullName>CustomerCategory__c</fullName>
    <label>Customer Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatingCompany__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Author</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Educational Institution</fullName>
            </value>
            <value>
                <fullName>Enterprise Market</fullName>
            </value>
            <value>
                <fullName>Government Agency</fullName>
            </value>
            <value>
                <fullName>Library</fullName>
            </value>
            <value>
                <fullName>Medical Institution</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Private Individual</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>School Group</fullName>
            </value>
            <value>
                <fullName>Trade Bookstore</fullName>
            </value>
            <value>
                <fullName>Trade Regular</fullName>
            </value>
            <value>
                <fullName>Trade Specialists</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Medical Institution - Care</fullName>
            </value>
            <value>
                <fullName>Medical Institution - Cure</fullName>
            </value>
            <value>
                <fullName>Tender Distributor</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
                <isActive>false</isActive>
                <label>Competitor</label>
            </value>
            <value>
                <fullName>Hospital</fullName>
                <isActive>false</isActive>
                <label>Hospital</label>
            </value>
            <value>
                <fullName>Private Person</fullName>
                <isActive>false</isActive>
                <label>Private Person</label>
            </value>
            <value>
                <fullName>School</fullName>
                <isActive>false</isActive>
                <label>School</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
            <value>
                <fullName>Supplier</fullName>
                <isActive>false</isActive>
                <label>Supplier</label>
            </value>
            <value>
                <fullName>Teacher</fullName>
                <isActive>false</isActive>
                <label>Teacher</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerDiscountGroup__c.field-meta.xml
<CustomField>
    <fullName>CustomerDiscountGroup__c</fullName>
    <label>Customer Discount Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CustomerCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CustomerDiscountGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DataMigrationHistory__c.field-meta.xml
<CustomField>
    <fullName>DataMigrationHistory__c</fullName>
    <description>Field to store the data migration history, to keep track when data was updated, by who and why it was updated.</description>
    <label>Data Migration History</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/DeliveryRouting__c.field-meta.xml
<CustomField>
    <fullName>DeliveryRouting__c</fullName>
    <description>This information is mandatory for Förlagssystem in the shipping messages sent from integrations.</description>
    <label>Delivery Routing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DeliveryRouting</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DigitalActivationEmail__c.field-meta.xml
<CustomField>
    <fullName>DigitalActivationEmail__c</fullName>
    <inlineHelpText>Default address for sending out activation notifications.</inlineHelpText>
    <label>Digital Activation Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalCustomerId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCustomerId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Schoolnumber or any other unique identifier of the customer.</inlineHelpText>
    <label>External Customer ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalDatabase__c.field-meta.xml
<CustomField>
    <fullName>ExternalDatabase__c</fullName>
    <label>External Database</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatingCompany__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agodi</fullName>
            </value>
            <value>
                <fullName>BRIN</fullName>
            </value>
            <value>
                <fullName>Informat</fullName>
            </value>
            <value>
                <fullName>RIO</fullName>
            </value>
            <value>
                <fullName>La Banque du Livre</fullName>
            </value>
            <value>
                <fullName>Skolverket</fullName>
            </value>
            <value>
                <fullName>UDB</fullName>
            </value>
            <value>
                <fullName>Bokinfo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InvoicingEmail__c.field-meta.xml
<CustomField>
    <fullName>InvoicingEmail__c</fullName>
    <description>Default Email address used for sending Invoices to the Account.</description>
    <inlineHelpText>This is the Default Email address, used to send Invoices to.</inlineHelpText>
    <label>Invoicing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/LegalName__c.field-meta.xml
<CustomField>
    <fullName>LegalName__c</fullName>
    <label>Legal Name (max 85 char)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MunicipalityName__c.field-meta.xml
<CustomField>
    <fullName>MunicipalityName__c</fullName>
    <description>SIMLINK attribute for Liber</description>
    <externalId>true</externalId>
    <label>Municipality Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <defaultValue>
        IF(ISPICKVAL($User.OperatingCompany__c, "Plantyn"), "Plantyn",
        IF(ISPICKVAL($User.OperatingCompany__c, "Liber"), "Liber",
        IF(ISPICKVAL($User.OperatingCompany__c, "Noordhoff"), "Noordhoff",
        IF(ISPICKVAL($User.OperatingCompany__c, "Noordhoff Zorg"), "Noordhoff Zorg",
        "")))) 
    </defaultValue>
    <label>Operating Company</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OperatingCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OrderNotificationEmail__c.field-meta.xml
<CustomField>
    <fullName>OrderNotificationEmail__c</fullName>
    <label>Order Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PhoneCountry__c.field-meta.xml
<CustomField>
    <fullName>PhoneCountry__c</fullName>
    <label>Phone Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingCostMethod__c.field-meta.xml
<CustomField>
    <fullName>ShippingCostMethod__c</fullName>
    <label>Shipping Indication Rule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ShippingCostMethod</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/AccountClassifications.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pre-school</fullName>
    </customValue>
    <customValue>
        <fullName>Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Upper Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Lower Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>Gymnasium/Vuxenutbildning</fullName>
    </customValue>
    <customValue>
        <fullName>Higher</fullName>
    </customValue>
    <customValue>
        <fullName>Högskola</fullName>
    </customValue>
    <customValue>
        <fullName>Generic</fullName>
    </customValue>
    <customValue>
        <fullName>Kompetensutveckling</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational</fullName>
    </customValue>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <customValue>
        <fullName>Professional</fullName>
    </customValue>
    <customValue>
        <fullName>SFI</fullName>
    </customValue>
    <customValue>
        <fullName>French Higher</fullName>
    </customValue>
    <customValue>
        <fullName>French Pre-school</fullName>
    </customValue>
    <customValue>
        <fullName>French Primary</fullName>
    </customValue>
    <customValue>
        <fullName>French Professional</fullName>
    </customValue>
    <customValue>
        <fullName>French Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>Upper Secondary</fullName>
        <isActive>false</isActive>
        <label>Upper Secondary</label>
    </customValue>
    <masterLabel>AccountClassifications</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Communication_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>nl_NL</fullName>
        <label>NL</label>
    </customValue>
    <customValue>
        <fullName>fr_FR</fullName>
        <label>FR</label>
    </customValue>
    <customValue>
        <fullName>en</fullName>
        <label>EN</label>
    </customValue>
    <customValue>
        <fullName>sv_SE</fullName>
        <label>SE</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <isActive>false</isActive>
        <label>DE</label>
    </customValue>
    <masterLabel>Communication Language</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Courier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DHL | DHL regelverk</fullName>
    </customValue>
    <customValue>
        <fullName>SCH | Schenker regelverk</fullName>
    </customValue>
    <customValue>
        <fullName>20 | Ekonomibrev</fullName>
    </customValue>
    <customValue>
        <fullName>21 | 1:A-Klassbrev</fullName>
    </customValue>
    <customValue>
        <fullName>26 | PostNord Parcel</fullName>
    </customValue>
    <customValue>
        <fullName>28 | PostNord Parcel 9.00</fullName>
    </customValue>
    <customValue>
        <fullName>29 | PostNord Parcel 12.00</fullName>
    </customValue>
    <customValue>
        <fullName>32 | Schenker Parcel Ombud</fullName>
    </customValue>
    <customValue>
        <fullName>73 | HÄMTAS – utan fraktsedel</fullName>
    </customValue>
    <customValue>
        <fullName>74 | HÄMTAS - med fraktsedel</fullName>
    </customValue>
    <customValue>
        <fullName>80 | Kungsbud</fullName>
    </customValue>
    <customValue>
        <fullName>84 | UPS standard</fullName>
    </customValue>
    <customValue>
        <fullName>85 | UPS saver</fullName>
    </customValue>
    <customValue>
        <fullName>44 | DHL</fullName>
        <isActive>false</isActive>
        <label>44 | DHL</label>
    </customValue>
    <masterLabel>Courier</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CustomerDiscountGroup.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Educational Institution</fullName>
    </customValue>
    <customValue>
        <fullName>Author</fullName>
    </customValue>
    <customValue>
        <fullName>Company</fullName>
    </customValue>
    <customValue>
        <fullName>Library</fullName>
    </customValue>
    <customValue>
        <fullName>Concern</fullName>
    </customValue>
    <customValue>
        <fullName>Trade (French Region)</fullName>
    </customValue>
    <customValue>
        <fullName>Government Agency (lower)</fullName>
    </customValue>
    <customValue>
        <fullName>Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Government Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Partner (French Region)</fullName>
    </customValue>
    <customValue>
        <fullName>Private Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Specialists</fullName>
    </customValue>
    <customValue>
        <fullName>Trade (direct debit)</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Regular</fullName>
    </customValue>
    <customValue>
        <fullName>Wolters Kluwer Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Staff</fullName>
    </customValue>
    <customValue>
        <fullName>Standaard Boekhandel</fullName>
    </customValue>
    <customValue>
        <fullName>Student</fullName>
    </customValue>
    <customValue>
        <fullName>Trade (Flemish Region)</fullName>
    </customValue>
    <customValue>
        <fullName>Partner (Flemish Region)</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Reseller</fullName>
    </customValue>
    <customValue>
        <fullName>School Group</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Bookstore</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Bookstore - No Discount</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Bookstore - Combined</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Bookstore 8%</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Bookstore 9%</fullName>
    </customValue>
    <customValue>
        <fullName>Trade Bookstore 20%</fullName>
    </customValue>
    <customValue>
        <fullName>Van Dijk</fullName>
    </customValue>
    <masterLabel>Customer Discount Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DeliveryRouting.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LIBAZ</fullName>
        <label>LIBAZ - Liber Amazon</label>
    </customValue>
    <customValue>
        <fullName>LIBBRE</fullName>
        <label>LIBBRE - Liber Letters</label>
    </customValue>
    <customValue>
        <fullName>LIBBUD</fullName>
        <label>LIBBUD - Liber Bud</label>
    </customValue>
    <customValue>
        <fullName>LIBDHL</fullName>
        <label>LIBDHL - Liber DHL</label>
    </customValue>
    <customValue>
        <fullName>LIBEXP</fullName>
        <label>LIBEXP - Liber Exports</label>
    </customValue>
    <customValue>
        <fullName>LIBHÄM</fullName>
        <label>LIBHÄM - Liber Pick up at WH</label>
    </customValue>
    <customValue>
        <fullName>LIBHÄS</fullName>
        <label>LIBHÄS - Hämtas Skuggan</label>
    </customValue>
    <customValue>
        <fullName>LIBMAK</fullName>
        <label>LIBMAK - Liber MAK</label>
    </customValue>
    <customValue>
        <fullName>LIBNRM</fullName>
        <label>LIBNRM - Liber Default</label>
    </customValue>
    <customValue>
        <fullName>LIBNÄR</fullName>
        <label>LIBNÄR - Liber Läromedia Örebro</label>
    </customValue>
    <customValue>
        <fullName>LIBPOS</fullName>
        <label>LIBPOS - Liber Postal</label>
    </customValue>
    <customValue>
        <fullName>LIBSCH</fullName>
        <label>LIBSCH - Liber Schenker</label>
    </customValue>
    <masterLabel>Delivery Routing</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OperatingCompany.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Liber</fullName>
    </customValue>
    <customValue>
        <fullName>Noordhoff</fullName>
    </customValue>
    <customValue>
        <fullName>Plantyn</fullName>
    </customValue>
    <customValue>
        <fullName>Infinitas Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Noordhoff Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Professional</fullName>
        <isActive>false</isActive>
        <label>Professional</label>
    </customValue>
    <masterLabel>Operating Company</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ShippingCostMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Based on weight Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>Based on weight non Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping Cost Exempt</fullName>
    </customValue>
    <customValue>
        <fullName>Based on order total</fullName>
    </customValue>
    <customValue>
        <fullName>Weight</fullName>
        <isActive>false</isActive>
        <label>Based upon fulfilment</label>
    </customValue>
    <customValue>
        <fullName>Exempt</fullName>
        <isActive>false</isActive>
        <label>Exempt</label>
    </customValue>
    <masterLabel>Shipping Indication Rule</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SK_createAccounts.cls
public class SK_createAccounts {

    public static Account createAccount(SK_SkolverketUpdateByAPI.schoolDetails sd, Map<String,Account> liberAccounts) {

        // set basic variables
        Id recordTypeId = [SELECT Id FROM Recordtype WHERE sObjectType = 'Account' AND Name = 'B2B Educational' LIMIT 1].Id;
        Date todaysDate = Date.today();

        // ALWAYS
        Account a = new Account();
        a.LegalName__c = sd.Namn;
        a.AgodiUpdateInProgress__c = true;

        // ONLY ON UPDATE
        if (liberAccounts.get(sd.Skolenhetskod) != null) {
            a.Id = liberAccounts.get(sd.Skolenhetskod).Id;
            a.DataMigrationHistory__c = 'Skolverket Update - ' + todaysDate;
        } 
        
        // ONLY ON INSERT
        else {
            a.DataMigrationHistory__c = 'Skolverket Insert - ' + todaysDate;
            a.RecordTypeId = recordTypeId;
            a.AccountSource = 'Skolverket';
            a.ExternalDatabase__c = 'Skolverket';
            a.ExternalCustomerId__c = sd.Skolenhetskod;
            a.Name = sd.Namn;
            a.OperatingCompany__c = 'Liber';
            a.PhoneCountry__c = 'Sweden';
            a.CommunicationLanguage__c = 'sv_SE';
            a.Courier__c = 'SCH | Schenker regelverk';
            a.DeliveryRouting__c = 'LIBSCH';
            if (sd.Telefon != null) {
                System.debug('ORIGINAL PHONE ==> ' + sd.Telefon);
                a.Phone = sd.Telefon.replace('-','').replace('.','').replace('/','').replace(' ','');
                While(a.Phone.left(1) == '0') {
                    a.Phone = a.Phone.substring(1);
                }
                if (a.Phone.left(1) != '+') {
                    a.Phone = '+' + a.Phone;
                }
                System.debug('PHONE ==> ' + a.Phone);
                System.debug('Phone Regex Match ==> ' + Pattern.matches('^\\+[1-9]\\d{1,14}$', a.Phone));
            }
            if (sd.Epost != null) {
                String emailAdres = sd.Epost;
                a.InvoicingEmail__c = emailAdres;
                a.OrderNotificationEmail__c = emailAdres;
                a.BillingReminderEmail__c = emailAdres;
                a.DigitalActivationEmail__c = emailAdres;
            }
            if (sd.Besoksadress?.Adress != null) {
                a.BillingStreet = sd.Besoksadress?.Adress;
                if (sd.Leveransadress?.Adress != null) {
                    a.ShippingStreet = sd.Leveransadress?.Adress;
                } else {
                    a.ShippingStreet = sd.Besoksadress?.Adress;
                }
            }
            if (sd.Besoksadress?.Postnr != null) {
                a.BillingPostalCode = sd.Besoksadress?.Postnr;
                if (sd.Leveransadress?.Postnr != null) {
                    a.ShippingPostalCode = sd.Leveransadress?.Postnr;
                } else {
                    a.ShippingPostalCode = sd.Besoksadress?.Postnr;
                }
            }
            if (sd.Besoksadress?.Ort != null) {
                a.BillingCity = sd.Besoksadress?.Ort;
                if (sd.Leveransadress?.Ort != null) {
                    a.ShippingCity = sd.Leveransadress?.Ort;
                } else {
                    a.ShippingCity = sd.Besoksadress?.Ort;
                }
            }
            if (sd.Kommun != null) {
                if (sd.kommun.Kommunkod != null & sd.kommun.Kommunkod != '') {
                    a.MunicipalityCode__c = sd.Kommun.Kommunkod;
                }
                if (sd.kommun.Namn != null && sd.kommun.Namn != '') {
                    a.MunicipalityName__c = sd.Kommun.Namn;
                }
            }
            a.BillingCountry = 'Sweden';
            a.ShippingCountry = 'Sweden';
            a.ShippingCostMethod__c = 'Based on weight Domestic';
            if (sd.Webbadress != null && sd.Webbadress != '') {
                if (sd.Webbadress.left(4).toLowerCase() == 'http') {
                    a.Website = sd.Webbadress.toLowerCase();
                } else {
                    a.Website = 'http://' + sd.Webbadress.toLowerCase();
                }
                System.debug('Webadress ==> ' + a.Website);
            }
            a.CustomerCategory__c = 'Educational Institution';
            a.CustomerDiscountGroup__c = a.CustomerCategory__c;
            if (sd.Skolformer.size() > 0) {
                String schoolProgramString = createSchoolProgramString(sd.Skolformer);
                if (schoolProgramString.length() > 1) {
                    a.SchoolPrograms__c = schoolProgramString;
                }
                String classificationString = createClassificationString(sd.Skolformer);
                if (classificationString.length() > 1) {
                    a.Classification__c = classificationString;
                }
            }
        }
        return a;
    }

    public static String createClassificationString(List<SK_SkolverketUpdateByAPI.Skolformer> sfList) {
        
        List<String> classificationList = new List<String>();
        Boolean Gymnasieskola = false;
        Boolean Grundskola = false;
        Boolean Specialskola = false;
        Boolean Sameskola = false;

        for (SK_SkolverketUpdateByAPI.Skolformer sf : sfList) {
            switch on sf.SkolformKod {
                when '1' {
                    Gymnasieskola = true;
                }
                when '5' {
                    Grundskola = true;
                }
                when '12' {
                    Specialskola = true;
                }
                when '15' {
                    Sameskola = true;
                }
            }
        }

        if (Gymnasieskola) {
            classificationList.add('Gymnasium/Vuxenutbildning');
        }
        if (Grundskola) {
            classificationList.add('Primary');
        }
        if (Specialskola) {
            classificationList.add('Primary');
        }
        if (Sameskola) {
            classificationList.add('Primary'); 
        }

        return String.join(classificationList, ';');
    }

    public static String createSchoolProgramString(List<SK_SkolverketUpdateByAPI.Skolformer> sfList) {

        Map<String, String> skolformerCodeTranslations = new Map<String, String>{
            'BA'    =>  'Bygg- och anläggningsprogrammet',
            'BF'    =>  'Barn- och fritidsprogrammet',
            'EE'    =>  'El- och energiprogrammet',
            'EK'    =>  'Ekonomiprogrammet',
            'ES'    =>  'Estetiska programmet',
            'FS'    =>  'Försäljnings- och serviceprogrammet',
            'FT'    =>  'Fordons- och transportprogrammet',
            'FX'    =>  'Flygteknikutbildningen',
            'HA'    =>  'Handels- och administrationsprogrammet',
            'HT'    =>  'Hotell- och turismprogrammet',
            'HU'    =>  'Humanistiska programmet',
            'HV'    =>  'Hantverksprogrammet',
            'I_P'   =>  'Industritekniska programmet',
            'MX'    =>  'Marinteknikutbildningen',
            'NA'    =>  'Naturvetenskapsprogrammet',
            'NB'    =>  'Naturbruksprogrammet',
            'RL'    =>  'Restaurang- och livsmedelsprogrammet',
            'SA'    =>  'Samhällsvetenskapsprogrammet',
            'SX'    =>  'Sjöfartsutbildningen',
            'TE'    =>  'Teknikprogrammet',
            'TX'    =>  'Tågteknikutbildningen',
            'UX'    =>  'Utbildningen samiska näringar',
            'VF'    =>  'VVS- och fastighetsprogrammet',
            'VO'    =>  'Vård- och omsorgsprogrammet',
            'YX'    =>  'Yrkesdansarutbildningen'
        };

        List<String> schoolProgramList = new List<String>();
        for (SK_SkolverketUpdateByAPI.Skolformer sf : sfList) {
            if (sf.SkolformKod == '1') {

                if (sf.BA) {
                    schoolProgramList.add(skolformerCodeTranslations.get('BA'));
                }
                if (sf.BF) {
                    schoolProgramList.add(skolformerCodeTranslations.get('BF'));
                }
                if (sf.EE) {
                    schoolProgramList.add(skolformerCodeTranslations.get('EE'));
                }
                if (sf.EK) {
                    schoolProgramList.add(skolformerCodeTranslations.get('EK'));
                }
                if (sf.ES) {
                    schoolProgramList.add(skolformerCodeTranslations.get('ES'));
                }
                if (sf.FS) {
                    schoolProgramList.add(skolformerCodeTranslations.get('FS'));
                }
                if (sf.FT) {
                    schoolProgramList.add(skolformerCodeTranslations.get('FT'));
                }
                if (sf.FX) {
                    schoolProgramList.add(skolformerCodeTranslations.get('FX'));
                }
                if (sf.HA) {
                    schoolProgramList.add(skolformerCodeTranslations.get('HA'));
                }
                if (sf.HT) {
                    schoolProgramList.add(skolformerCodeTranslations.get('HT'));
                }
                if (sf.HU) {
                    schoolProgramList.add(skolformerCodeTranslations.get('HU'));
                }
                if (sf.HV) {
                    schoolProgramList.add(skolformerCodeTranslations.get('HV'));
                }
                if (sf.I_P) {
                    schoolProgramList.add(skolformerCodeTranslations.get('I_P'));
                }
                if (sf.MX) {
                    schoolProgramList.add(skolformerCodeTranslations.get('MX'));
                }
                if (sf.NA) {
                    schoolProgramList.add(skolformerCodeTranslations.get('NA'));
                }
                if (sf.NB) {
                    schoolProgramList.add(skolformerCodeTranslations.get('NB'));
                }
                if (sf.RL) {
                    schoolProgramList.add(skolformerCodeTranslations.get('RL'));
                }
                if (sf.SA) {
                    schoolProgramList.add(skolformerCodeTranslations.get('SA'));
                }
                if (sf.SX) {
                    schoolProgramList.add(skolformerCodeTranslations.get('SX'));
                }
                if (sf.TE) {
                    schoolProgramList.add(skolformerCodeTranslations.get('TE'));
                }
                if (sf.TX) {
                    schoolProgramList.add(skolformerCodeTranslations.get('TX'));
                }
                if (sf.UX) {
                    schoolProgramList.add(skolformerCodeTranslations.get('UX'));
                }
                if (sf.VF) {
                    schoolProgramList.add(skolformerCodeTranslations.get('VF'));
                }
                if (sf.VO) {
                    schoolProgramList.add(skolformerCodeTranslations.get('VO'));
                }
                if (sf.YX) {
                    schoolProgramList.add(skolformerCodeTranslations.get('YX'));
                }

            }
        }


        return String.join(schoolProgramList,';');
    }
}