force-app/main/default/objects/Account/fields/NetsuiteInternalId__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteInternalId__c</fullName>
    <label>Internal Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountSubsidiary__c/AccountSubsidiary__c.object-meta.xml
<CustomObject>
    <label>Account Subsidiary</label>
    <nameField>
        <displayFormat>Acc Sub {000000}</displayFormat>
        <label>Subsidiary No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Subsidiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountSubsidiary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Subsidiaries</relationshipLabel>
    <relationshipName>Account_Subsidiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountSubsidiary__c/fields/AccountSubsidiary__c.field-meta.xml
<CustomField>
    <fullName>AccountSubsidiary__c</fullName>
    <formula>Account__r.CustomerNumber__c  + &quot;-&quot;+  SubsidiaryName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Subsidiary</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSubsidiary__c/fields/NetsuiteInternalId__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite Internal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/AccountSubsidiary__c.field-meta.xml
<CustomField>
    <fullName>AccountSubsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Subsidiary</label>
    <referenceTo>AccountSubsidiary__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/NetSuiteIdAccountSubsidiary__c.field-meta.xml
<CustomField>
    <fullName>NetSuiteIdAccountSubsidiary__c</fullName>
    <label>NetSuiteId Account Subsidiary</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zRemove Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products (Account)</relationshipLabel>
    <relationshipName>OrderProducts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AccountSubsidiary__c.field-meta.xml
<CustomField>
    <fullName>AccountSubsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Subsidiary</label>
    <referenceTo>AccountSubsidiary__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/NetsuiteInternalId__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteInternalId__c</fullName>
    <label>NetSuiteId Account Subsidiary</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ShipToAccount__c.field-meta.xml
<CustomField>
    <fullName>ShipToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ship To Line Items</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/FixedStartDate__c.field-meta.xml
<CustomField>
    <fullName>FixedStartDate__c</fullName>
    <description>If a product has a seasonal period in which it is valid (e.g. digital subscriptions for schools), this is the date it starts at.</description>
    <label>Fixed Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Report_Emailer_Setting__mdt/fields/Report_Export_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Export_File_Name__c</fullName>
    <inlineHelpText>This will be the file name of the export. Eg: filename.csv</inlineHelpText>
    <label>Report Export File Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Report_Emailer_Setting__mdt/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <label>Report Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Report_Emailer_Setting__mdt/fields/Report_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Name__c</fullName>
    <label>Report Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReportEmailerSchedulerTest.cls
@isTest
public class ReportEmailerSchedulerTest {
    public static testMethod void ReportEmailerSchedulerTest() {
        /*Report rep = [SELECT Id FROM Report LIMIT 1]; // NEED A REPORT TO TEST
@isTest(SeeAllData = true)
        Report_Emailer_Setting__mdt customMetaData = new Report_Emailer_Setting__mdt();
        customMetaData.Report_Export_File_Name__c = 'TestExport';
        customMetaData.Report_Id__c = rep.Id;
        customMetaData.Report_Name__c = 'Test Export';
        customMetaData.Recipient_Email__c = 'connor@cloudmuscle.nl';
        insert customMetaData;*/
        test.startTest();
        List<Account> lstAccount = TestDataFactory.insertAccountsSubsidiary(2, 'Noordhoff',true,true);

    List<Id> Set_AccId = new List<Id>();
        for(Account acc:lstAccount){
            Set_AccId.add(acc.id);
        }

        Order_AccountSubsidiary.AccountSubsidiary(Set_AccId);

        AccountSubsidiary__c[] lstAccountSubsidiary = [Select id,Account__c from AccountSubsidiary__c where Account__c in:Set_AccId ];

        Map<String,String> Map_AccSub = new Map<String,String>();
        Integer i=0;
        for(AccountSubsidiary__c  sub:lstAccountSubsidiary){
            sub.NetsuiteInternalId__c = '88776'+i;
            Map_AccSub.put(sub.Account__c,sub.id);
            i++;
        }

        update lstAccountSubsidiary;

        List<Product2> lstProduct = TestDataFactory.insertProducts(3,false);
        for(Product2 prod:lstProduct){
            prod.FixedStartDate__c = null;
        }
        insert lstProduct;

        Pricebook2 standardPricebook = TestDataFactory.insertPricebook();
        List<PricebookEntry> lstPricebookEntry = TestDataFactory.insertPricebookEntry(standardPricebook.id ,lstProduct,true);
        List<Contract> lstContract = TestDataFactory.insertContract(1,lstAccount,standardPricebook.id,true);
        List<Order> lstOrder = TestDataFactory.insertOrderHeader(1,lstAccount,lstContract,standardPricebook.id,false);
        List<OrderItem> lstOrderItems = TestDataFactory.insertOrderItems(1,lstAccount,Map_AccSub,lstOrder,lstPricebookEntry,false);


        List<Id> RecordIds = new List<Id>();
        Set<Id> Set_RecordIds = new Set<Id>();
        for(Order ord:lstOrder){
            system.debug('**Map_AccSub**'+Map_AccSub.get(ord.AccountId));
            ord.AccountSubsidiary__c = Map_AccSub.get(ord.AccountId); 
            ord.NetSuiteIdAccountSubsidiary__c = '12345';
          //  RecordIds.add(ord.id);
           // Set_RecordIds.add(ord.id);
        }
        Insert lstOrder;

        for(OrderItem item:lstOrderItems){
            system.debug('**Map_AccSub**'+Map_AccSub.get(item.ShipToAccount__c));
            item.AccountSubsidiary__c = Map_AccSub.get(item.ShipToAccount__c); 
            item.OrderId = lstOrder[0].id;
        }

        insert lstOrderItems;

        
        ReportEmailerScheduler s = new ReportEmailerScheduler();
        s.execute(null);
        test.stopTest();
    }
}