force-app/main/default/objects/Account/fields/NetsuiteInternalId__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteInternalId__c</fullName>
    <label>Internal Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address</label>
    <referenceTo>ILAddress__c</referenceTo>
    <relationshipLabel>Accounts (Shipping Address)</relationshipLabel>
    <relationshipName>ShippingAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountSubsidiary__c/AccountSubsidiary__c.object-meta.xml
<CustomObject>
    <label>Account Subsidiary</label>
    <nameField>
        <displayFormat>Acc Sub {000000}</displayFormat>
        <label>Subsidiary No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Subsidiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountSubsidiary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Subsidiaries</relationshipLabel>
    <relationshipName>Account_Subsidiaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountSubsidiary__c/fields/AccountSubsidiary__c.field-meta.xml
<CustomField>
    <fullName>AccountSubsidiary__c</fullName>
    <formula>Account__r.CustomerNumber__c  + &quot;-&quot;+  SubsidiaryName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Subsidiary</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSubsidiary__c/fields/NetsuiteInternalId__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteInternalId__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite Internal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILAddress__c/ILAddress__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ILAddress__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zRemove Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/AccountSubsidiary__c.field-meta.xml
<CustomField>
    <fullName>AccountSubsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Subsidiary</label>
    <referenceTo>AccountSubsidiary__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/BillToAddress__c.field-meta.xml
<CustomField>
    <fullName>BillToAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-To Address</label>
    <referenceTo>ILAddress__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShipToAddress__c.field-meta.xml
<CustomField>
    <fullName>ShipToAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship-To Address</label>
    <referenceTo>ILAddress__c</referenceTo>
    <relationshipLabel>Orders (Ship-To Address)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zRemove Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products (Account)</relationshipLabel>
    <relationshipName>OrderProducts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/AccountSubsidiary__c.field-meta.xml
<CustomField>
    <fullName>AccountSubsidiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Subsidiary</label>
    <referenceTo>AccountSubsidiary__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/BillToAddress__c.field-meta.xml
<CustomField>
    <fullName>BillToAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill-To Address</label>
    <referenceTo>ILAddress__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/NetsuiteInternalId__c.field-meta.xml
<CustomField>
    <fullName>NetsuiteInternalId__c</fullName>
    <label>NetSuiteId Account Subsidiary</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ShipToAddress__c.field-meta.xml
<CustomField>
    <fullName>ShipToAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship-To Address</label>
    <referenceTo>ILAddress__c</referenceTo>
    <relationshipLabel>Order Products (Ship-To Address)</relationshipLabel>
    <relationshipName>Order_Products_Ship_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddressValidationTest.cls
@isTest
public class AddressValidationTest {
    @testSetup static void createTestData(){
        //create Account
        List<Account> lstAccount = TestDataFactory.insertAccounts(1, 'Plantyn', false);
        insert lstAccount;
        Set<String> Set_AccId = new Set<String>();
        for(Account acc:lstAccount){
            Set_AccId.add(acc.id);
        }
        
        AccountSubsidiary__c[] lstAccountSubsidiary = [Select id,Account__c from AccountSubsidiary__c where Account__c in:Set_AccId ];
        
        Map<String,String> Map_AccSub = new Map<String,String>();
        Integer i=0;
        for(AccountSubsidiary__c  sub:lstAccountSubsidiary){
            sub.NetsuiteInternalId__c = '88776'+i;
            Map_AccSub.put(sub.Account__c,sub.id);
            i++;
            
        }
        
        update lstAccountSubsidiary;
        
        List<Product2> lstProduct = TestDataFactory.insertProducts(3,true);
        Pricebook2 standardPricebook = TestDataFactory.insertPricebook();
        List<PricebookEntry> lstPricebookEntry = TestDataFactory.insertPricebookEntry(standardPricebook.id ,lstProduct,true);
        List<Contract> lstContract = TestDataFactory.insertContract(1,lstAccount,standardPricebook.id,true);
        List<Order> lstOrder = TestDataFactory.insertOrderHeader(1,lstAccount,lstContract,standardPricebook.id,false);
        for(Order ord : lstOrder){
            ord.BillToAddress__c = lstAccount[0].ShippingAddress__c;
            ord.ShipToAddress__c = lstAccount[0].ShippingAddress__c;
        }
        insert lstOrder;
        
        List<OrderItem> lstOrderItems = TestDataFactory.insertOrderItems(1,lstAccount,Map_AccSub,lstOrder,lstPricebookEntry,false);
        for(OrderItem ordIt : lstOrderItems){
            ordIt.ShipToAddress__c = lstAccount[0].ShippingAddress__c;
            ordIt.OrderStatus__c = 'Draft';
        }
        
        insert lstOrderItems;
    }
    
    @isTest
    public static void testAddressImportOrderInvocable(){
        List<Account> testAcc = [SELECT Id FROM Account];
        List<ILAddress__c> addies = [SELECT Id from ILAddress__c];
            
        List<AddressValidation.Request> requests = new List<AddressValidation.Request>();
        AddressValidation.Request request = new AddressValidation.Request();
        request.street = 'DePijp';
        request.housenumber = '22';
        request.housenumberAddition = '';
        request.postalcode = '1224AM';
        request.country = 'Netherlands';
        request.accountId = testAcc[0].Id;
        requests.add(request);
        
        test.startTest();
        AddressValidation.validateAddress(requests);
        boolean updated = AddressValidation.updateOrdersANDOrderItems(addies[0].Id, true);
        test.stopTest();
    }
    
}