force-app/main/default/objects/Account/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <defaultValue>
        IF(ISPICKVAL($User.OperatingCompany__c, "Plantyn"), "Plantyn",
        IF(ISPICKVAL($User.OperatingCompany__c, "Liber"), "Liber",
        IF(ISPICKVAL($User.OperatingCompany__c, "Noordhoff"), "Noordhoff",
        IF(ISPICKVAL($User.OperatingCompany__c, "Noordhoff Zorg"), "Noordhoff Zorg",
        "")))) 
    </defaultValue>
    <label>Operating Company</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OperatingCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CategoryLevel1__c.field-meta.xml
<CustomField>
    <fullName>CategoryLevel1__c</fullName>
    <label>Category Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>OperatingCompany__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CategoryLevel1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CategoryLevel2__c.field-meta.xml
<CustomField>
    <fullName>CategoryLevel2__c</fullName>
    <label>Category Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CategoryLevel1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CategoryLevel2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ContactFirstName__c.field-meta.xml
<CustomField>
    <fullName>ContactFirstName__c</fullName>
    <formula>IF(ISNULL(ContactId), &apos;&apos;, Contact.FirstName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact FirstName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.OperatingCompany__c, &quot;Plantyn&quot;), &quot;Plantyn&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Liber&quot;), &quot;Liber&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff&quot;), &quot;Noordhoff&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff Professional&quot;), &quot;Noordhoff&quot;,
&quot;&quot;))))</defaultValue>
    <label>Operating Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OperatingCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Liber.recordType-meta.xml
<RecordType>
    <fullName>Liber</fullName>
    <active>true</active>
    <businessProcess>Support Process</businessProcess>
    <label>Liber</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Noordhoff.recordType-meta.xml
<RecordType>
    <fullName>Noordhoff</fullName>
    <active>true</active>
    <businessProcess>Support Process</businessProcess>
    <label>Noordhoff</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Plantyn.recordType-meta.xml
<RecordType>
    <fullName>Plantyn</fullName>
    <active>true</active>
    <businessProcess>Support Process</businessProcess>
    <label>Plantyn</label>
</RecordType>

force-app/main/default/objects/Contact/fields/OperatingCompany__c.field-meta.xml
<CustomField>
    <fullName>OperatingCompany__c</fullName>
    <defaultValue>IF(ISPICKVAL($User.OperatingCompany__c, &quot;Plantyn&quot;), &quot;Plantyn&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Liber&quot;), &quot;Liber&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff&quot;), &quot;Noordhoff&quot;,
IF(ISPICKVAL($User.OperatingCompany__c, &quot;Noordhoff Zorg&quot;), &quot;Noordhoff Zorg&quot;,
&quot;&quot;))))</defaultValue>
    <label>Operating Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OperatingCompany</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CategoryLevel1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General</fullName>
    </customValue>
    <customValue>
        <fullName>Primary Education</fullName>
    </customValue>
    <customValue>
        <fullName>Secondary Education</fullName>
    </customValue>
    <customValue>
        <fullName>Vocational Education</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>Hoger onderwijs</fullName>
        <isActive>false</isActive>
        <label>Hoger onderwijs</label>
    </customValue>
    <customValue>
        <fullName>Middelbaar beroepsonderwijs</fullName>
        <isActive>false</isActive>
        <label>Middelbaar beroepsonderwijs</label>
    </customValue>
    <customValue>
        <fullName>Voortgezet onderwijs</fullName>
        <isActive>false</isActive>
        <label>Voortgezet onderwijs</label>
    </customValue>
    <customValue>
        <fullName>Basisonderwijs</fullName>
        <isActive>false</isActive>
        <label>Basisonderwijs</label>
    </customValue>
    <customValue>
        <fullName>Algemeen</fullName>
        <isActive>false</isActive>
        <label>Algemeen</label>
    </customValue>
    <masterLabel>Category Level 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CategoryLevel2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assortiment</fullName>
    </customValue>
    <customValue>
        <fullName>Bestelling &amp; Levering</fullName>
    </customValue>
    <customValue>
        <fullName>Klantgegevens &amp; Account</fullName>
    </customValue>
    <customValue>
        <fullName>Factuur &amp; Betaling</fullName>
    </customValue>
    <customValue>
        <fullName>Werken met het digitaal lesmateriaal</fullName>
    </customValue>
    <customValue>
        <fullName>Privacy</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>Werken met het digitaal materiaal</fullName>
        <isActive>false</isActive>
        <label>Werken met het digitaal materiaal</label>
    </customValue>
    <masterLabel>Category Level 2</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OperatingCompany.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Liber</fullName>
    </customValue>
    <customValue>
        <fullName>Noordhoff</fullName>
    </customValue>
    <customValue>
        <fullName>Plantyn</fullName>
    </customValue>
    <customValue>
        <fullName>Infinitas Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Noordhoff Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Professional</fullName>
        <isActive>false</isActive>
        <label>Professional</label>
    </customValue>
    <masterLabel>Operating Company</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MAIL_mailChildCases_BATCH_TEST.cls
@IsTest
public  class MAIL_mailChildCases_BATCH_TEST {

    @TestSetup
    static void makeData(){

        List<Account> accounts = UTIL_TestDatafactory.createAccounts(1, true);
        List<Contact> contacts = UTIL_TestDatafactory.createContacts(4, accounts, true);


        // Get Noordhoff Case recordtypeId
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Noordhoff').getRecordTypeId();

        // Get Noordhoff BusinessHoursId
        Id businessHoursId = [SELECT Id FROM BusinessHours WHERE Name = 'Noordhoff' LIMIT 1].Id;

        // Create Parent Cases
        List<Case> parentCases = new List<Case>();
        for (String OpCo : new List<String>{'Noordhoff','Plantyn','Liber','Noordhoff Zorg'}) {
            Case pC = new Case();
            pC.recordTypeId = recordTypeId;
            pC.Subject = 'Test ParentCase';
            pC.Type = 'Problem';
            pC.Status = 'New';
            pC.Origin = 'Phone';
            // pC.CategoryLevel1__c = 'General';
            // pC.CategoryLevel2__c = 'Assortiment';
            pC.BusinessHoursId = businessHoursId;
            if (OpCo != 'Noordhoff Zorg') {
                pC.ContactId = contacts[contacts.size()-1].Id;
            } else {
                pC.SuppliedEmail = 'testSuppliedEmail@test.invalid';
                pC.suppliedName = 'Test SuppliedName';
            }
            pC.OperatingCompany__c = OpCo;
            parentCases.add(pC);
        }

        insert parentCases;

        // Create child Cases
        List<Case> childCases = new List<Case>();
        for (Integer i = 0; i < 3; i++) {
            Case cC = new Case();
            cC.recordTypeId = recordTypeId;
            cC.Subject = 'Test ChildCase ' + (i + 1);
            cC.ParentId = parentCases[i].Id;
            cC.Type = 'Question';
            cC.Status = 'New';
            cC.Origin = 'Phone';
            // cC.CategoryLevel1__c = 'General';
            // cC.CategoryLevel2__c = 'Assortiment';
            cC.BusinessHoursId = businessHoursId;
            if (i > 0) {
                cC.ContactId = contacts[i].Id;
            } else {
                cC.SuppliedEmail = 'testSuppliedEmail@test.invalid';
                cC.suppliedName = 'Test SuppliedName';
            }
            cC.OperatingCompany__c = parentCases[i].OperatingCompany__c;
            childCases.add(cC);
        }
        insert childCases;
    }

    @IsTest
    static void TestNoordhoff(){
        
        MAIL_mailChildCases_BATCH.FlowInputs fi = new MAIL_mailChildCases_BATCH.FlowInputs();
        fi.parentCase = [SELECT Id FROM Case WHERE Type = 'Problem' AND OperatingCompany__c = 'Noordhoff' LIMIT 1];
        fi.childCases = [SELECT Id, ContactEmail, ContactId, ContactFirstName__c, SuppliedName, SuppliedEmail, ParentId, OperatingCompany__c FROM Case WHERE Type = 'Question'];
        fi.title = 'Test title';
        fi.body ='Test Body';
        fi.doMailParentCase = true;

        List<MAIL_mailChildCases_BATCH.FlowInputs> fiLst = new List<MAIL_mailChildCases_BATCH.FlowInputs>();
        fiLst.add(fi);
        
        Test.startTest();
            MAIL_mailChildCases_BATCH.sendEmailToChildCases(fiLst);
        Test.stopTest();
    }

    @IsTest
    static void TestPlantyn(){

        MAIL_mailChildCases_BATCH.FlowInputs fi = new MAIL_mailChildCases_BATCH.FlowInputs();
        fi.parentCase = [SELECT Id FROM Case WHERE Type = 'Problem' AND OperatingCompany__c = 'Plantyn' LIMIT 1];
        fi.childCases = [SELECT Id, ContactEmail, ContactId, ContactFirstName__c, SuppliedName, SuppliedEmail, ParentId, OperatingCompany__c FROM Case WHERE Type = 'Question'];
        fi.title = 'Test title';
        fi.body ='Test Body';
        fi.doMailParentCase = true;

        List<MAIL_mailChildCases_BATCH.FlowInputs> fiLst = new List<MAIL_mailChildCases_BATCH.FlowInputs>();
        fiLst.add(fi);
        
        Test.startTest();
            MAIL_mailChildCases_BATCH.sendEmailToChildCases(fiLst);
        Test.stopTest();
    }

    @IsTest
    static void TestLiber(){

        MAIL_mailChildCases_BATCH.FlowInputs fi = new MAIL_mailChildCases_BATCH.FlowInputs();
        fi.parentCase = [SELECT Id FROM Case WHERE Type = 'Problem' AND OperatingCompany__c = 'Liber' LIMIT 1];
        fi.childCases = [SELECT Id, ContactEmail, ContactId, ContactFirstName__c, SuppliedName, SuppliedEmail, ParentId, OperatingCompany__c FROM Case WHERE Type = 'Question'];
        fi.title = 'Test title';
        fi.body ='Test Body';
        fi.doMailParentCase = true;

        List<MAIL_mailChildCases_BATCH.FlowInputs> fiLst = new List<MAIL_mailChildCases_BATCH.FlowInputs>();
        fiLst.add(fi);
        
        Test.startTest();
            MAIL_mailChildCases_BATCH.sendEmailToChildCases(fiLst);
        Test.stopTest();
    }

    @IsTest
    static void TestZorg(){

        MAIL_mailChildCases_BATCH.FlowInputs fi = new MAIL_mailChildCases_BATCH.FlowInputs();
        fi.parentCase = [SELECT Id FROM Case WHERE Type = 'Problem' AND OperatingCompany__c = 'Noordhoff Zorg' LIMIT 1];
        fi.childCases = [SELECT Id, ContactEmail, ContactId, ContactFirstName__c, SuppliedName, SuppliedEmail, ParentId, OperatingCompany__c FROM Case WHERE Type = 'Question'];
        fi.title = 'Test title';
        fi.body ='Test Body';
        fi.doMailParentCase = true;

        List<MAIL_mailChildCases_BATCH.FlowInputs> fiLst = new List<MAIL_mailChildCases_BATCH.FlowInputs>();
        fiLst.add(fi);
        
        Test.startTest();
            MAIL_mailChildCases_BATCH.sendEmailToChildCases(fiLst);
        Test.stopTest();
    }
}