force-app/main/default/objects/ILAddress__c/ILAddress__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ILAddress__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>zRemove Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ILAddress__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ILAddress__c/fields/HouseNumber__c.field-meta.xml
<CustomField>
    <fullName>HouseNumber__c</fullName>
    <label>House Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ILAddress__c/fields/HouseNumberAddition__c.field-meta.xml
<CustomField>
    <fullName>HouseNumberAddition__c</fullName>
    <label>House Number Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressImportOrderInvocableTest.cls
@isTest
public without sharing class AddressImportOrderInvocableTest {

    @testSetup static void createTestData(){
        //create Account
        List<Account> testAcc = TestDataFactory.insertAccounts(1, 'Plantyn', false);
        insert testAcc;
        //create ILAddress__c
        ILAddress__c accountShippinAddress = new ILAddress__c();
        accountShippinAddress.Account__c = testAcc[0].Id;
        accountShippinAddress.Street__c = 'DePijp';
        accountShippinAddress.HouseNumber__c = '22';
        accountShippinAddress.HouseNumberAddition__c = '';
        accountShippinAddress.PostalCode__c = '1224AM';
        accountShippinAddress.City__c = 'Amsterdam';
        accountShippinAddress.Country__c = 'Netherlands';
        insert accountShippinAddress;
    }
    
    @isTest
    public static void testAddressImportOrderInvocable(){
        List<Account> testAcc = [SELECT Id FROM Account];
            
        List<AddressValidation.Request> requests = new List<AddressValidation.Request>();
        AddressValidation.Request request = new AddressValidation.Request();
        request.street = 'DePijp';
        request.housenumber = '22';
        request.housenumberAddition = '';
        request.postalcode = '1224AM';
        request.country = 'Netherlands';
        request.accountId = testAcc[0].Id;
        requests.add(request);
        
        test.startTest();
        AddressImportOrderInvocable.validateImportOrderAddress(requests);
        test.stopTest();
    }
    
}